googleapis/discovery-artifact-manager

- src/snippetgen/compilecheck/internal/nodejs/parselib.go
- src/snippetgen/compilecheck/internal/nodejs/parselib_test.go
The Node.js client library switched to TypeScript recently. This commit
updates the file extension that compilecheck looks for.
> Use TypeScript file extensions

- src/main/common/updatedisco.go
1. Prevent APIs from being updated with past versions
Sometimes, multiple consecutive requests to the Discovery service
return Discovery documents with different revision tags.
This commit adds a check to verify that the downloaded Discovery
document has a revision that is at least as recent as the one that
already exists (if one already exists).
If the revision check fails, the update process for that particular
Discovery document is aborted as a no-op without an error.
2. Error on non-200 Discovery document responses
This commit also adds a check for non-200 responses from Discovery
URLs. There are some cases where the Discovery directory lists APIs
which point to missing Discovery documents. In the case that a
non-200 response is returned from a Discovery document URL, an error
is …
> Fix 404 and past revision behavior

- server/tasks/_check_output.py
- server/tests/test__check_output.py
Contains a convenient wrapper over `subprocess.check_output` which
raises a nice exception containing stdout and stderr information on
failure.
> Add _check_output module

- server/tasks/__init__.py
- server/tasks/accounts.py
- server/tests/test_accounts.py
Contains definitions and getters for the various accounts the server
needs access to.
Account information is retrieved from Datastore.
> Add accounts module

- discoveries/content.v2.json
Force update of the content v2 discovery document.
It is currently failing to update automatically because the previous discovery document had a revision field but the new discovery document has no revision field. The current [updatedisco script](https://github.com/googleapis/discovery-artifact-manager/blob/master/src/main/common/updatedisco.go#L229) flags this as an error.
This is causing https://github.com/google/google-api-ruby-client/issues/691 downstream.
This PR performs a forced manual update of the content_v2 discovery doc from https://www.googleapis.com/discovery/v1/apis/content/v2/rest to remove the blockage for that one API, which is a current high priority issue (see internal issue b/111153891). I'll file a separate issue or PR for the general problem.
> Force update of content v2 discovery

- src/main/common/updatedisco.go
If a disco does not have a revision, do not do revision check when updating.
Fix #86
> Fix revision check

- gapic/google/compute/v1/compute_gapic.yaml
Ran `artman --config=gapic/google/compute/artman_compute.yaml --root-dir=`pwd` --local generate discogapic_config`
on latest compute.v1.json.
Successfully generated a client from this config afterwards.
> Regenerate compute_gapic.yaml

- gapic/google/compute/v1/compute_gapic.yaml
Just regenerated compute_gapic.yaml from gapic-generator. Apparently resource_object_method config has become unsupported since last regen.
> Regen compute_gapic.yaml from gapic-generator:master

- WORKSPACE
gapic-generator just started using v1.13.0-pre2 in https://github.com/googleapis/gapic-generator/pull/2394
> Update common-protos dep to match gapic-generator

- server/Dockerfile
Testing generated libraries is failing with Go 1.8. Bumping to 1.11.
> Update Go version to 1.11

- server/tasks/google_api_php_client_services.py
[google-apis-client-generator v1.6.0](https://pypi.org/project/google-apis-client-generator/1.6.0/) includes a few required fixes in the PHP generation process.
/cc @bshaffer
> Require latest version of google-apis-client-generator

- toolkit/src/main/java/com/google/api/codegen/discovery/config/ruby/RubyTypeNameGenerator.java
- toolkit/src/main/java/com/google/api/codegen/discovery/transformer/SampleNamer.java
- toolkit/src/main/java/com/google/api/codegen/discovery/transformer/csharp/CSharpSampleNamer.java
- toolkit/src/main/java/com/google/api/codegen/discovery/transformer/js/JSSampleNamer.java
The `canonicalName` for `iam` API is `iam` which is not `UpperCamel`. Allow creating ApiTypeName from `anyCamel` names to allow us generate samples for `iam`.
> Allow creating ApiTypeName from anyCamel

- server/app.yaml
- server/main.py
- server/tasks/google_api_php_client_services.py
- server/tasks/google_api_ruby_client.py
- PHP can now utilize per API batch paths. (https://github.com/google/apis-client-generator/commit/747c6215659df6d8e694eb15ad010d42bedce01a)
- Temporarily disabled generation of the health care service for PHP/Ruby pending a more complete fix.
- Increased appengine memory limit to help prevent timeouts.
/cc @hzyi-google When you have a moment could you please take a look?
> Various apiary fixes

- server/app.yaml
Go apiary builds are continuing to be fail due to running out of memory. Nudging this value up a bit to hopefully resolve this in the short term, but we may want to look into a more permanent solution.
> Increase memory allocation

- server/main.py
- server/tasks/google_api_ruby_client.py
We had previously halted generation of the Cloud HealthCare clients due to issues with `$`s in method names. A fix is being pushed to the service which will resolve this.
Please hold off on merging until we get the ok the service is updated in production.
> Re-enable cloud health care generation for PHP/ruby

- toolkit/src/main/resources/com/google/api/codegen/nodejs/sample.snip
Our authentication API is now promise based, and has in general a slightly different API signature than documented in these historic samples.
> fix: example of fetching auth client does not match API

- gapic/google/compute/v1/compute_gapic.yaml
- toolkit/build.gradle
- toolkit/src/main/java/com/google/api/codegen/configgen/DiscoConfigGeneratorTool.java
As a reference for future refreshes, this update was done as follows:
1. from the `toolkit/` directory, run:
```
./gradlew runDiscoConfigGen '-Pclargs=--discovery_doc=../discoveries/compute.v1.json,-output=../gapic/google/compute/v1/compute_gapic.yaml'
```
2. manually edit the top packaging section of the yaml so it matches previous versions
This PR also includes the new gradle rule `runDiscoConfigGen` used
above, and clarifies the relevant command-line flag.
This should lead to https://github.com/googleapis/google-cloud-java/issues/5471 being resolved.
> Refresh compute_gapic.yaml, and make it clearer how to do so

- gapic/google/compute/v1/compute_gapic.yaml
Previously generated gapic config for compute was generated by toolkit in this repo, which has been out of date. Regenerate it with the latest gapic-generator.
Was able to successfully generate the client with a local artman.
> Regenerate Compute gapic config

- server/main.py
websecurityscanner:v1 shouldn't be in the list returned from https://www.googleapis.com/discovery/v1/apis, we need to prevent generation until this is resolved upstream.
> Prevent generation of websecurityscanner:v1 for PHP

- server/Dockerfile
Update Ruby from 2.3 to 2.6.5 in the GAE app image.
This is because Ruby 2.3 is past EOL, and the Ruby client libraries team is in the process of updating all Ruby libraries to require Ruby 2.4 or later. So we need to update the Ruby used to build google-api-ruby-client. Version 2.6.5 is the latest stable version as of Oct 2019.
Note: Ubuntu 16_04 doesn't have packages for a later version, so we fall back on the Ruby community's tools for building/installing Ruby.
> Update Ruby to 2.6.5

- WORKSPACE
- gapic/google/compute/v1/BUILD.bazel
- gapic/google/compute/v1/compute_gapic.yaml
Also update `compute_gapic.yaml`.
Note, the checked in `cumpute_gapic.yaml` is not used for bazel generation and is kept here only for backward compatibility with artman generation. Bazel generates the gapic file on the fly.
> fix: Fix bazel generation for discogapic clients.

- server/Dockerfile
- server/tasks/google_api_go_client.py
The way this was managing the dependencies used for Go was not
honoring modules. This caused the apiaries to be built with HEAD
of deps. There was a recent change in one of our deps that broke on
us when using head. We should now use modules for building the code.
Note, the ennvar is explicitly not set for the `go get` command.
> fix go generation

- server/Dockerfile
- server/tasks/google_api_go_client.py
There seems to be something strange where GO111MODULE=on is not
being honored by the `make all` command. I believe this is because
the code was in GOPATH.
Removed the need for GOPATH by making use of git to download the
src code.
> refactor Go generation

- server/Dockerfile
- server/tasks/google_api_go_client.py
Turning on Go modules broke other Go code in this repo. Reverting global `GO111MODULE=on` for now, this should eventually be updated.
> fix disco updates

- .gitignore
- run_tests.py
- toolkit/src/main/java/com/google/api/codegen/discovery/transformer/py/PythonSampleMethodToViewTransformer.java
- toolkit/src/main/resources/com/google/api/codegen/py/discovery_fragment.snip
- toolkit/src/main/resources/com/google/api/codegen/py/sample.snip
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_appengine.v1beta5.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_bigquery.v2.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_cloudbilling.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_clouddebugger.v2.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_cloudmonitoring.v2beta2.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_cloudresourcemanager.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_cloudtrace.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_clouduseraccounts.beta.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_compute.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_container.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_datastore.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_datastore.v1beta3.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_deploymentmanager.v2.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_dns.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_genomics.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_healthcase.v1beta1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_logging.v2beta1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_prediction.v1.6.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_pubsub.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_replicapoolupdater.v1beta1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_sqladmin.v1beta4.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_storage.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_storagetransfer.v1.json.baseline
- toolkit/src/test/java/com/google/api/codegen/testdata/discoveries/py/py_vision.v1.json.baseline
Fixes #152
* discoGen jar is generated via `cd toolkit && ./gradlew discoJar`
* `cd toolkit && ./gradlew test` passes
* I also modified run_test.py to produce override with `'authType': 'APPLICATION_DEFAULT_CREDENTIALS'` and ran `./run_tests.py -l python discoveries/cloudbilling.v1.json`. All tests also passed as soon as I generated default credentials via `gcloud auth application-default login` and all generated code samples looked sane.
> Replacing deprecated oauth2client with google-auth

- server/cron.yaml
because the new cron job discoveries-pr creates a pull request that's automatically merged.
> chore: drop old cron job that pushed to master branch

- server/cron.yaml
Ruby is migrating to release-please and autorelease. Disable weekly dartman-driven releases by deleting the cron entry.
> chore: Delete weekly Ruby release cron

- .github/workflows/list-services.yml
fixes https://github.com/googleapis/discovery-artifact-manager/issues/6142
Index is not a service, so it should be excluded from the list of services.
> fix: remove "index" from services

- .github/workflows/normalize-disco.yml
- scripts/normalize_discovery.py
A manually triggered one-off action/script to create a PR like: https://github.com/googleapis/discovery-artifact-manager/pull/10699
Future discovery docs are already being normalized in the update_disco.py script, but it won't be updated in the directory until there is a new revision with substantial changes. This will normalize all the existing docs in place (sorted keys, consistent indentation) so future diffs are readable/reviewable.
> build: add workflow to normalize discovery docs

- README.md
docs: remove outdated information
docs: note that legacy code is deprecated
> docs: clarify discovery document cache expectations
